import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { ChartJSNodeCanvas } from "chartjs-node-canvas";

const width = 600;
const height = 300;
const chartMaker = new ChartJSNodeCanvas({ width, height });

export const generateMISPDF = async (data, officer) => {
    const fileName = `mis-report-${Date.now()}.pdf`;
    const filePath = path.join("reports", fileName);

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // HEADER
    try {
        doc.image("logo.png", 50, 20, { width: 60 });
    } catch (e) { }

    doc.fontSize(22).text("Management Information System Report", 130, 40);
    doc.moveDown(3);

    doc.fontSize(12).text(`Generated For: ${officer.name}`);
    doc.text(`Role: ${officer.role}`);
    doc.text(`Generated At: ${new Date().toLocaleString()}`);
    doc.moveDown(2);

    // BENEFICIARY SECTION
    doc.fontSize(16).text("1. Beneficiary Summary", { underline: true });
    doc.moveDown(1);

    doc.fontSize(12).text(`Total Beneficiaries: ${data.beneficiaries.total}`);
    doc.moveDown(2);

    // VERIFICATION SECTION
    doc.fontSize(16).text("2. Verification Summary", { underline: true });
    doc.moveDown(1);

    doc.fontSize(12).text(`Total Verifications: ${data.verifications.total}`);
    doc.moveDown(1);

    doc.text("Status Breakdown:");
    data.verifications.breakdown.forEach(item => {
        doc.text(`   • ${item._id}: ${item.count}`);
    });
    doc.moveDown(2);

    // FEEDBACK SECTION
    doc.fontSize(16).text("3. Feedback & Sentiment Summary", { underline: true });
    doc.moveDown(1);

    doc.fontSize(12).text(
        `Average Sentiment Score: ${data.feedback.avgSentiment.toFixed(2)}`
    );
    doc.text(`Total Feedback Entries: ${data.feedback.totalFeedbacks}`);
    doc.moveDown(2);

    // CHART SECTION
    const labels = data.verifications.breakdown.map(i => i._id);
    const values = data.verifications.breakdown.map(i => i.count);

    const chartBuffer = await chartMaker.renderToBuffer({
        type: "bar",
        data: {
            labels,
            datasets: [{
                label: "Verification Count",
                data: values
            }]
        }
    });

    const chartImg = path.join("reports", `chart-${Date.now()}.png`);
    fs.writeFileSync(chartImg, chartBuffer);

    doc.image(chartImg, { width: 500, align: "center" });
    doc.moveDown(3);

    // FOOTER
    doc.fontSize(10).text("Generated by SUJHAA", {
        align: "center"
    });

    doc.end();

    setTimeout(() => fs.unlinkSync(chartImg), 300);

    return filePath;
};
